id = "razen"
name = "Razen Language"
description = "Language support for Razen programming language (.rzn files) with syntax highlighting, auto-completion, and intelligent code features"
version = "0.1.0"
schema_version = 1
authors = ["Razen Language Team <team@razen-lang.org>"]
repository = "https://github.com/BasaiCorp/Razen-Lang"
homepage = "https://razen-lang.org"

[grammars.razen]
repository = "https://github.com/tree-sitter/tree-sitter-rust"
rev = "0431a2c60828731f27491ee9fdefe25e250ce9c9"
path = "."

[[languages]]
name = "razen"
grammar = "razen"
path_suffixes = ["rzn"]
scope = "source.razen"